"""Redshift Translator for the MCP Adapter Layer.

Translates StructuredIntent payloads into mcp-redshift tool calls by
reusing the existing SQLGenerator for SQL construction and delegating
query execution to the MCP Redshift server via MCPClientManager.
"""

from __future__ import annotations

import logging
from typing import TYPE_CHECKING

from src.models.redshift_models import GeneratedQuery, SQLGeneratorError
from src.models.shared import AgentResult, StructuredIntent

from .client_manager import MCPClientManager, MCPTimeoutError, MCPUnavailableError
from .models import MCPToolResult

if TYPE_CHECKING:
    from src.services.sql_generator import SQLGenerator

logger = logging.getLogger(__name__)


class RedshiftTranslator:
    """Translates StructuredIntent to mcp-redshift tool calls.

    Reuses the existing SQLGenerator to produce parameterized SQL, then
    invokes execute_parameterized_query on the MCP Redshift server.
    Fetches table schema via describe_table if not cached.
    """

    def __init__(
        self, sql_generator: SQLGenerator, client: MCPClientManager
    ) -> None:
        """Initialize the Redshift translator.

        Args:
            sql_generator: Existing SQLGenerator instance for SQL construction.
            client: MCPClientManager connected to the mcp-redshift server.
        """
        self.sql_generator = sql_generator
        self.client = client
        self._schema_cache: dict[str, list[dict]] = {}

    async def execute(self, intent: StructuredIntent) -> AgentResult | MCPToolResult:
        """Generate SQL and execute via MCP Redshift server.

        Calls SQLGenerator.generate() with the intent. On success, invokes
        execute_parameterized_query. On SQLGeneratorError, returns an error
        AgentResult directly without calling MCP.

        Args:
            intent: The StructuredIntent targeting Redshift entities.

        Returns:
            MCPToolResult on successful MCP invocation, or AgentResult on
            SQL generation error or MCP failure.
        """
        # Generate SQL via existing SQLGenerator
        result = self.sql_generator.generate(intent)

        if isinstance(result, SQLGeneratorError):
            # Short-circuit: return error AgentResult without MCP call
            logger.info(
                "SQLGenerator returned error for query %s: %s",
                intent.query_id,
                result.error_type,
            )
            return AgentResult(
                status="error",
                error_type=result.error_type,
                error_description=result.description,
                agent_id="mcp-redshift-adapter",
                data_source="mcp-redshift",
            )

        # We have a GeneratedQuery - ensure schema is cached
        assert isinstance(result, GeneratedQuery)
        await self._ensure_schema_cached(result.table_name)

        # MCP execute_query doesn't support parameterized queries —
        # inline parameter values into the SQL string (safe because values
        # are generated by our own NLP pipeline, not raw user input).
        sql = result.sql
        if result.parameters:
            sql = self._inline_parameters(sql, result.parameters)

        # MCP server wraps queries with its own LIMIT/OFFSET for pagination.
        # Strip any LIMIT clause from our SQL to avoid double-LIMIT syntax errors.
        import re
        limit_match = re.search(r'\bLIMIT\s+(\d+)\s*$', sql, re.IGNORECASE)
        mcp_limit = None
        if limit_match:
            mcp_limit = int(limit_match.group(1))
            sql = sql[:limit_match.start()].rstrip()

        # Invoke MCP execute_query tool with the finalized SQL
        try:
            tool_args: dict = {"sql": sql}
            if mcp_limit is not None:
                tool_args["limit"] = mcp_limit

            mcp_result = await self.client.call_tool(
                "execute_query",
                tool_args,
            )
            return mcp_result

        except MCPTimeoutError as e:
            logger.error(
                "MCP Redshift execute_query timed out for query %s",
                intent.query_id,
            )
            return AgentResult(
                status="error",
                error_type="MCP_TOOL_ERROR",
                error_description=(
                    f"mcp-redshift execute_query timed out: {e}"
                ),
                agent_id="mcp-redshift-adapter",
                data_source="mcp-redshift",
            )

        except MCPUnavailableError as e:
            logger.error(
                "MCP Redshift server unavailable for query %s: %s",
                intent.query_id,
                str(e),
            )
            # Re-raise so the caller (service layer) can trigger fallback
            raise

    async def _ensure_schema_cached(self, table_name: str) -> None:
        """Fetch and cache table schema via describe_table if not cached.

        Args:
            table_name: The Redshift table name to describe.
        """
        if table_name in self._schema_cache:
            return

        try:
            result = await self.client.call_tool(
                "describe_table",
                {"schema": "public", "table": table_name},
            )
            if result.success and result.content:
                columns = result.content.get("columns", [])
                self._schema_cache[table_name] = columns
                logger.debug(
                    "Cached schema for table %s (%d columns)",
                    table_name,
                    len(columns),
                )
            else:
                logger.warning(
                    "describe_table for %s returned error: %s",
                    table_name,
                    result.error_message,
                )
        except (MCPTimeoutError, MCPUnavailableError) as e:
            # Schema cache miss is non-fatal; SQL generation already has
            # the schema from SchemaRegistry. Log and continue.
            logger.warning(
                "Could not cache schema for table %s via MCP: %s",
                table_name,
                str(e),
            )

    def clear_schema_cache(self) -> None:
        """Clear the cached table schemas."""
        self._schema_cache.clear()

    @staticmethod
    def _inline_parameters(sql: str, parameters: list[dict]) -> str:
        """Inline named parameter values into SQL for MCP execution.

        Replaces :param_name placeholders with properly quoted values.
        Boolean values are rendered as TRUE/FALSE, strings as 'quoted',
        and numbers as-is.

        Args:
            sql: SQL string with :param_name placeholders.
            parameters: List of {"name": "param_name", "value": value} dicts.

        Returns:
            SQL string with values inlined.
        """
        for param in parameters:
            name = param["name"]
            value = param["value"]
            placeholder = f":{name}"

            # Format value for SQL
            if isinstance(value, bool):
                sql_value = "TRUE" if value else "FALSE"
            elif isinstance(value, (int, float)):
                sql_value = str(value)
            else:
                # String value — escape single quotes and wrap
                escaped = str(value).replace("'", "''")
                sql_value = f"'{escaped}'"

            sql = sql.replace(placeholder, sql_value)

        return sql
